included:
  - Sources
excluded:
  - Configs
  - DerivedData
  - Tests
  - .idea
  - .build
  - Package.swift
whitelist_rules:
  # - closure_parameter_position
  # - extension_access_modifier
  # - file_header
  # - operator_usage_whitespace
  # - operator_whitespace
  # - sorted_imports
  # - switch_case_on_newline
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - control_statement
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - fatal_error_message
  - file_length
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - let_var_whitespace
  - line_length
  - mark
  - missing_docs
  - multiline_parameters
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - notification_center_detachment
  - number_separator
  - object_literal
  - opening_brace
  - overridden_super_call
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - strict_fileprivate
  - syntactic_sugar
  - todo
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_docs
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate

line_length:              120
identifier_name:
  excluded:
    - R
    - r
    - id
number_separator:
  minimum_length:         5
nesting:
  type_level:
    warning:              2
colon:
  flexible_right_spacing: true
