#!/usr/bin/env bash
#
# Downloads cocoapods dependencies

set -euo pipefail
IFS=$'\n\t'

cd "${0%/*}/../Dependencies"

# bundle exec pod repo update
bundle exec pod install
rsync -a Rome/ ../Frameworks/ --remove-source-files
rm -rf Rome
